# wireguard
interface: wg0

# 使用するポート番号を変更する際は、インスタンス作成手順のファイアウォール・ルール開放ポート番号(firewall_rules_open_port)も合わせて変更
port: 59820

ipv4: 
  network: 192.168.242.0
  netmask: 255.255.255.0

ipv6:
  network: fd00::c0a8:f200
  netmask: 120

